curl -H "User-Agent: HandyGuitarLab/1.0" -o DynaComp.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RossComp.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Compulator.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MultiComp.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o dbx160A.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o UREI1176.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o OrangeSq.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RackComp.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o StudioComp.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o OptComp.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Limiter.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o NoiseGate.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DirtyGate.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ZNR.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SlowGate.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o LineSel.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Mute.zip https://zoom.co.jp
