curl -H "User-Agent: HandyGuitarLab/1.0" -o Booster7.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MassiveBoost.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o CalBoost.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o G5nBoost.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o EpBoost.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SoloBoost.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TrebleBoost.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o CleanBoost.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o CustomBoost.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o FatBoost.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RC_Drive.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o AC_Drive.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TimmyOd.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o JanRay.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SweetDrive.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Z_Drive.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o KlonCentaur.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o CentaurOd.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HoneyBee.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MorningGlry.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BB_Preamp.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SparkBoost.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MooerPure.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Tumnus.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Archer.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SoulFood.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o PrinceOfTone.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o KingOfTone.zip https://zoom.co.jp
