curl -H "User-Agent: HandyGuitarLab/1.0" -o FuzzFace.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BigMuff.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ToneBender.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o OctFuzz.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o FuzzFactory.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SwollenPickle.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o GatedFuzz.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MuffPi.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RussianMuff.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TriangleMuff.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RamHeadMuff.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o OpAmpMuff.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Fuzzrite.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MaestroFZ.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o UnivoxSuper.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ZvexFuzz.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o WoollyMamm.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o VelvetFuzz.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HoofFuzz.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o PharaohFuz.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ChromaFuz.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Octavia.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Tycobrahe.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ShinEi_FY.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Supafuzz.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Buzzaround.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SpaghettiFz.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o IndustrialFz.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o OctaveUpFz.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o VelcroFuzz.zip https://zoom.co.jp
