curl -H "User-Agent: HandyGuitarLab/1.0" -o Booster.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o OverDrive.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TS_Drive.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o GoldDrive.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SweetDrive.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RedCrunch.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Distortion.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RatDist.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o FuzzFace.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BigMuff.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MetalWRLD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HotBox.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o GovDrive.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ZenDrive.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SmasherDS.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HM2_Metal.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MT2_Zone.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BossDS2.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DOD_250.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Octavia.zip https://zoom.co.jp
