curl -H "User-Agent: HandyGuitarLab/1.0" -o Chorus.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Detune.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o StereoCho.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Trichorus.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o CloneCho.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ChorusOne.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o VintageCE.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SilkyCho.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BaChorus.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o CoronaCho.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o CoronaTri.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Ensemble.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Mirage.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Phaser.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DuoPhase.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o WarpPhase.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o StonePha.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TheVibe.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Flanger.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DynaFlngr.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BaFlanger.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Vibrato.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Tremolo.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DuoTrem.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Slicer.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o AutoPan.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o PitchVibe.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o OctVibe.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Rotary.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o OrganRot.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o PitchSft.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BaPitch.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HPS.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o M-Pitch.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MonoPitch.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o PedalVxb.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BendCho.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RingMod.zip https://zoom.co.jp
