curl -H "User-Agent: HandyGuitarLab/1.0" -o Hall.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Room.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Plate.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Spring.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Arena.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Church.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TileRoom.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o GateRev.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HD_Hall.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HD_Room.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o EarlyRef.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o AirReverb.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ShimmerRev.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o IceReverb.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MangledSp.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BlackHole.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SpaceHole.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DualRev.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DynaReverb.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TremReverb.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ModReverb.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o LoFiReverb.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o OctReverb.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o PitchRev.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SlapReverb.zip https://zoom.co.jp
