curl -H "User-Agent: HandyGuitarLab/1.0" -o Delay.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o StompDly.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o StereoDly.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o AnalogDly.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BaAnaDly.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TapeEcho3.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DualDigiD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o CarbonDly.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MultiTapD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o PingPongD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SlapBackD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ModDelay.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o PhaseDly.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DriveEcho.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ReverseD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o PitchDly.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o IceDelay.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o LoFiDelay.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SlowAtkD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TremoloD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o FilterPPD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o AutoPanD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o CycleDly.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o StutterDly.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TrgHoldD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DynaDelay.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HoldDelay.zip https://zoom.co.jp
