curl -H "User-Agent: HandyGuitarLab/1.0" -o AutoWah_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Resonance_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Cry_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SeqFLTR_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RndmFLTR_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o GtGEQ_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ParaEQ_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Exciter_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SaxGEQ_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TpGEQ_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o VnGEQ_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HmGEQ_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o LowCut_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HighCut_1U.zip https://zoom.co.jp
