curl -H "User-Agent: HandyGuitarLab/1.0" -o Comp_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RackComp_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o GrayComp_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BlackOpt_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SlowATTCK_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ZNREng_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o NoiseGate_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MuteSW_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o LineSel_1U.zip https://zoom.co.jp
