curl -H "User-Agent: HandyGuitarLab/1.0" -o Chorus_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BaChorus_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Detune_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Flanger_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BaFlanger_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Phaser_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Tremolo_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o PitchSft_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BaPitch_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Defret_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MonoPitch_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Vibrato_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TheVibe_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o AutoPan_1U.zip https://zoom.co.jp
