curl -H "User-Agent: HandyGuitarLab/1.0" -o AGChorus_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SaxChorus_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HmChorus_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o StereoCho_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Detune_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Flanger_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Phaser_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RndPhaser_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Tremolo_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o PitchSft_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HPS_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Vibrato_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TheVibe_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o AutoPan_1U.zip https://zoom.co.jp
