curl -H "User-Agent: HandyGuitarLab/1.0" -o AutoWah.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Resonance.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o StepFilter.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SeqFilter.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RandomFilter.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o 4BandEQ.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o 7BandEQ.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ParaEQ.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o GuitarGEQ.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BottomB.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SubOct.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o AutoPan.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o LowCut.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HighCut.zip https://zoom.co.jp
