curl -H "User-Agent: HandyGuitarLab/1.0" -o Chorus.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o StereoCho.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Trichorus.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o CloneCho.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o CoronaCho.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Ensemble.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Detune.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Flanger.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Phaser.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TheVibe.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Vibrato.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Tremolo.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DuoTrem.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o PitchSft.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HPS.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RingMod.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Slicer.zip https://zoom.co.jp
