curl -H "User-Agent: HandyGuitarLab/1.0" -o Chorus_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o StereoCho_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o CoronaTri_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Detune_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Flanger_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o VinFLNGR_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Phaser_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Tremolo_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o PitchSft_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HPS_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RingMod_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o CloneCho_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Vibrato_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TheVibe_1U.zip https://zoom.co.jp
