curl -H "User-Agent: HandyGuitarLab/1.0" -o FD_DLXR_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o FD_BMAN_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HW_100_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MS_1959_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MS_800_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o VX_AC30_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o OR_120_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MATCH_30_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BG_XTNSY_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DZ_DRIVE_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RECTI_G_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o PV_5150_1U.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MS_CRIMSON_1U.zip https://zoom.co.jp
