curl -H "User-Agent: HandyGuitarLab/1.0" -o RatDist.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DS1_Dist.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MetalZ.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DistortionX.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SmasherDS.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ExtremeDS.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RiotDist.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o GuvnorDS.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o CrunchBox.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o PinnacleDS.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o FriedmanDS.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DiezelDS.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HM2_Metal.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MT2_Zone.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BossDS2.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ProCoRat.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TurboRat.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MXR_Dist.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DOD_250.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o GuyatoneOD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BognerUbers.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MesaThrot.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o EVH_5150.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o FriedmanBE.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DiezelVH4.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o EnglPower.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Peavey6505.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BognerSharp.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RandallDist.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SoldanoDist.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o KrakenDist.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ApexDist.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HorizonPrg.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RevvG3.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RevvG4.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SuhrRiot.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o WamplerTrp.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o JHS_Angry.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o EmpressHeavy.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o OkkoDiablo.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o EmmaReeza.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MI_AudioGI.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BlackstarDS.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Tech21Sans.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MarshallJack.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ShredMaster.zip https://zoom.co.jp
