curl -H "User-Agent: HandyGuitarLab/1.0" -o TS808_HW.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TS9.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TS9DX.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TS808.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MaxonOD9.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o GreenOd.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o TurboTS.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o OcdDrive.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RevoDrive.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o GridSlam.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ZenDrive.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BluesBrd.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o GovDrive.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SD1_Drive.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o OD1_Drive.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BD2_Driver.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o FullDrive2.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DynaDrive.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HotBox.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o GuvnorOD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o CrunchBox.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o PinnacleOD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RiotOD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o FriedmanOD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o DiezelOD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BognerEcst.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MesaFlux.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SuhrShiba.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o XoticBB.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Lovepedal.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o VoodooLab.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o CrowtherHot.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o KeeleyMod.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Analogman.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o JHS_808.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o WamplerPlex.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o MadProfOD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BarberLTD.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o HermidaZen.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o WayHugePrk.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o NobelsODR.zip https://zoom.co.jp
