curl -H "User-Agent: HandyGuitarLab/1.0" -o Ac_360.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o AL_750.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o AmpegSVT.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BaDI.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BaG_Kru.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o B-Man.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Darkglass.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o D_Pre.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o E_Pre.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o FlipTop.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Hartke.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o M_Pre.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Monotone.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o N_Pre.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SansAmp.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o S_Pre.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SVT_DI.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o T_Pre.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o V_Pre.zip https://zoom.co.jp
