curl -H "User-Agent: HandyGuitarLab/1.0" -o AutoFilter.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BaA-Wah.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BaAutoWah.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BaCryFltr.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BaGEQ.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BaParaEQ.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BaPEQ.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BaResoFltr.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o BottomB.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Defret.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o EnvelopeFilter.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Exciter.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o LineSel.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o Mute.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o RandomFilter.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SeqFilter.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SlowAttack.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o StBassGEQ.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o StepFilter.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o SubOct.zip https://zoom.co.jp
curl -H "User-Agent: HandyGuitarLab/1.0" -o ZTronFilter.zip https://zoom.co.jp
